spring:
  application:
    name: ms-transaction
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers: localhost:9092
      group-id: ms-transaction-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  data:
    mongodb:
      uri: mongodb://localhost:27017/bootcamp

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,info
      base-path: /actuator
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
    tags:
      application: ms-transaction
      environment: development
  endpoint:
    health:
      show-details: always
      show-components: always
      group:
        circuit-breaker:
          include: circuitBreakerHealth
        readiness:
          include: db,kafka
    prometheus:
      enabled: true
  health:
    circuitbreaker:
      enabled: true
    diskspace:
      enabled: true
    livenessState:
      enabled: true
    readinessState:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      account-validation:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 2s
  timelimiter:
    instances:
      account-validation:
        cancelRunningFuture: true
        timeoutDuration: 5s
